### ISSUE TITLE
Scala 2.12

### ISSUE THREAD

**Issue by devsprint** [dimafeng/testcontainers-scala#2]
Hi, is there any chance to build it agains scala 2.12.1 ? I will try to create a PR today or tomorrow.

**Comment by devsprint** [comment]
@dimafeng will you push 0.3.1 through maven central ?

**Comment by dimafeng** [comment]
@devsprint I uploaded it to oss.sonatype.org and released yesterday but for some reason it wasn't promoted to maven central. I'm going to investigate why that's happening.

**Comment by dimafeng** [comment]
Something is wrong with oss.sonatype.org -  https://issues.sonatype.org/browse/MVNCENTRAL-1443

**Comment by devsprint** [comment]
@dimafeng Thanks. I will wait than...

**Comment by dimafeng** [comment]
@devsprint just checked - 0.3.1 is not in the maven index, but you can add to your dependencies and it'll work.

**Comment by dimafeng** [comment]
*Maven*

```xml
<!-- Scala 2.11.* -->
<dependency>
    <groupId>com.dimafeng</groupId>
    <artifactId>testcontainers-scala_2.11</artifactId>
    <version>0.4.0</version>
    <scope>test</scope>
</dependency>

<!-- Scala 2.12.* -->
<dependency>
    <groupId>com.dimafeng</groupId>
    <artifactId>testcontainers-scala_2.12</artifactId>
    <version>0.4.0</version>
    <scope>test</scope>
</dependency>
```

*Gradle*

```groovy
testCompile("com.dimafeng:testcontainers-scala_2.11:0.4.0") // Scala 2.11.*
testCompile("com.dimafeng:testcontainers-scala_2.12:0.4.0") // Scala 2.12.*
```

*SBT*

```scala
libraryDependencies += "com.dimafeng" % "testcontainers-scala_2.11" % "0.4.0" % "test" // Scala 2.11.*
libraryDependencies += "com.dimafeng" % "testcontainers-scala_2.12" % "0.4.0" % "test" // Scala 2.12.*
```
