### ISSUE TITLE
TestContainers org

### ISSUE THREAD

**Issue by bsideup** [dimafeng/testcontainers-scala#4]
Hi!

Since TestContainers is an OpenSource organization on GitHub, it's possible to move your awesome project under https://github.com/testcontainers, so it'll be easier for people to discover it, and probably contribute!

You can continue to develop it the way you want to :)

What do you think?

**Comment by bsideup** [comment]
We're planning to extract testcontainers-core without JUnit dependency BTW :)

**Comment by dimafeng** [comment]
Hi @bsideup, this sounds interesting but how this will look like?
1. Will I have to publish artifacts under the `org.testcontainers` groupId and change my packaging from `com.dimafeng` to `org.testcontainers`?
2. Are organization members going to contribute directly to the repository?

> We're planning to extract testcontainers-core without JUnit dependency BTW :)

This is a really good news 👍

**Comment by bsideup** [comment]
1. well, it's up to you. We can keep it, or change, whatever works for you :)
2. Well, not now, also you're going to be the one who makes the decisions, no worries ;) We also love PRs instead of accessing the repo directly, so you'll have a chance to review the changes.

Our motivation is to keep everything testcontainers-related close to it. Your Scala bindings are great, I think they are the most powerful bindings for TestContainers in the wild, and it would be nice to have it under the organization, so people will see that they are, well, like "official Scala bindings for TestContainers". Cool, huh? :)

**Comment by bsideup** [comment]
We're not going to force any technology or decision; it's not like joining Apache :D Just an umbrella org

**Comment by dimafeng** [comment]
Sounds good. What do I need to do to proceed?

**Comment by bsideup** [comment]
1. (optionally) Join our Slack, so we can discuss it there: http://slack.testcontainers.org
2. I'll ask @rnorth to create a repo under https://github.com/testcontainers, `testcontainers-scala` sounds good, so we'll keep it. Also, if you prefer, we could fork it. Just say which option is better for you.
3. You will push your sources to the repo and continue the development there.
4. Would be nice if you add some note to this repo that it was forked and should be tracked under /testcontainers

**Comment by dimafeng** [comment]
1. I'll join soon.
2-3. I think a fork works for me.
4. Will do.

**Comment by bsideup** [comment]
https://github.com/testcontainers/testcontainers-scala

Repo was forked and should have access.
