### ISSUE TITLE
Compilation problems when using GenericContainer

### ISSUE THREAD

**Issue by zaharidichev** [dimafeng/testcontainers-scala#5]
@dimafeng 

The moment I touch GenericContainer class I get the following errors: 

```
[error] Class org.testcontainers.shaded.javax.annotation.CheckForNull not found - continuing with a stub.
[error] Class org.testcontainers.shaded.javax.annotation.CheckForNull not found - continuing with a stub.
[error] Class org.testcontainers.shaded.javax.annotation.CheckForNull not found - continuing with a stub.

[error] Class org.testcontainers.shaded.javax.annotation.CheckForNull not found - continuing with a stub.
[error] Class org.testcontainers.shaded.javax.annotation.CheckForNull not found - continuing with a stub.
[error] Class org.testcontainers.shaded.javax.annotation.CheckForNull not found - continuing with a stub.
```

Scala Version: 2.11.8
Sbt version: 0.13.8

Have tried changing scala and sbt versions without much success. This error really does not tell me much of what I need (e.g. where is this class needed at all ?). Is this some conflict with other libraries. For example is lombock's NonNull getting mixed up with findbug's NonNull. If that is the case I have excluded the latter dependency but still get errors. A bit of help will be greatly appreciated

**Comment by dimafeng** [comment]
https://github.com/testcontainers/testcontainers-scala/issues/11
