### ISSUE TITLE
scala 2.10

### ISSUE THREAD

**Issue by zlosim** [dimafeng/testcontainers-scala#6]
Hi,
would it be possible to build against scala 2.10.* and get it on maven central?

thanks a lot :)

**Comment by dimafeng** [comment]
Hi @zlosim,
I've just tried to build it against scala 2.10.7 and all tests passed so I guess it works. I'll publish it to maven central later today.

Btw, the project has moved to https://github.com/testcontainers/testcontainers-scala you can find more recent info in there

**Comment by dimafeng** [comment]
@zlosim 
Please check version 0.13.0, it's now available for scala 2.10

**Comment by dimafeng** [comment]
@zlosim sorry, I released as 0.13.1 by mistake
