### ISSUE TITLE
Not able to restart MySQLContainer within test case.

### ISSUE THREAD

**Issue by ujali** [dimafeng/testcontainers-scala#7]
Hi,

I have been trying to simulate an environment where network connection is not available for a while. For that I stopped my mysql container with command **mysqlContainer.container.getDockerClient.stopContainerCmd(mysqlContainer.container.getContainerId).exec()** as mysqlContainer.container.stop() command removed the container. However, when I try to start the container  **mysqlContainer.container.getDockerClient.execStartCmd(mysqlContainer.container.getContainerId)** or  **mysqlContainer.container.getDockerClient.startContainerCmd(mysqlContainer.container.getContainerId).exec()**, it does not seem to start the container.
I am using inbuilt MySQLContainer of testcontainers.
is there any work around to test the scenario?

class Test extends FlatSpecLike with ForAllTestContainer with ScalaFutures  {
  override implicit val patienceConfig: PatienceConfig = PatienceConfig(
    timeout = scaled(Span(10, Seconds)),
    interval = scaled(Span(500, Milliseconds)))

  val mysqlContainer = MySQLContainer()
  it should "restart container" in {
    val connection: Connection = DriverManager.getConnection(mysqlContainer.jdbcUrl, mysqlContainer.username, mysqlContainer.password)
    mysqlContainer.container.getDockerClient.stopContainerCmd(mysqlContainer.container.getContainerId).exec()
    println("Stopped container:::::::" + connection.isValid(3))
    mysqlContainer.container.getDockerClient.startContainerCmd(mysqlContainer.container.getContainerId).exec()
   Thread.sleep(50000) //only provided to check for if it is taking time to be up
    println("Start container::::::::" + connection.isValid(10))

    assert(connection.isValid(3))
  }
}

Console Output:

2018-01-08 11:57:26 INFO  🐳 [mysql:latest]:91 - Obtained a connection to container (jdbc:mysql://localhost:32797/test)
2018-01-08 11:57:26 INFO  🐳 [mysql:latest]:237 - Container mysql:latest started
Mon Jan 08 11:57:29 GST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Stopped container:::::::false
Start container::::::::false
[info] - should restart container *** FAILED ***
[info]   connection.isValid(3) was false (Test.scala:498)

Thank you

**Comment by dimafeng** [comment]
Hi @ujali
I think your case is a bit tricky and I would avoid stopping of the container since it breaks the testcontainer's lifecycle. 
To solve your problem, the best solution (per my current understanding) is:
1. build your own container with mysql and start it via `supervisord`. When you need to simulate network issues, you just stop the child mysql process (not the entire container)
-or-
2. build your own container with mysql and a firewall, then you can just drop all incoming/outcoming packets when you need it via shell command

In both scenarios, you will be using raw `GenericContainer`, all utility method which are missing (`getJdbcUrl`, ...) you can take from `org.testcontainers.containers.MySQLContainer`

**Comment by dimafeng** [comment]
Project has moved to  https://github.com/testcontainers/testcontainers-scala
Please use that project for further assistance
